BookUser\Entity\User:
  type: entity
  table: users
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    username:
      type: string
      length: 255
      unique: true
      nullable: true
    email:
      type: string
      length: 255
      unique: true
      nullable: true
    displayName:
      type: string
      length: 50
      nullable: true
    password:
      type: string
      length: 128
    state:
      type: smallint
      nullable: true
  manyToMany:
    roles:
      targetEntity: BookUser\Entity\Role
      joinTable:
        name: users_roles
        joinColumns:
          user_id:
            referencedColumnName: id
        inverseJoinColumns:
          role_id:
            referencedColumnName: id

