Library\Entity\Book:
  type: entity
  table: book
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      nullable: false
    author:
      type: string
      nullable: false
    description:
      type: text
      nullable: true
    cover:
      type: string
      nullable: true
    file:
      type: string
      nullable: true
  manyToOne:
    user:
      targetEntity: BookUser\Entity\User
      inversedBy: books
      joinColumn:
        name: user_id
        referencedColumnName: id
        onDelete: CASCADE
  oneToMany:
    reviews:
      targetEntity: Library\Entity\Review
      mappedBy: book