Library\Entity\Review:
  type: entity
  table: review
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    text:
      type: string
      nullable: false
  manyToOne:
    user:
      targetEntity: BookUser\Entity\User
      inversedBy: reviews
      joinColumn:
        name: user_id
        referencedColumnName: id
    book:
      targetEntity: Library\Entity\Book
      inversedBy: reviews
      joinColumn:
        name: book_id
        referencedBolumnName: id