Library\Entity\Book:
  type: entity
  table: book
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      nullable: false
    author:
      type: string
      nullable: false
    description:
      type: text
      nullable: true