<h1>Recent books</h1>
<div class="container">
    <div class="row">
        <?php foreach ($this->books as $book): ?>
            <div class="col-lg-3 col-sm-3 col-xs-6">
                <a class="thumbnail"
                   href="<?php echo $this->url('book', array('action' => 'view', 'id' => $book->getId())); ?>">
                    <img class="img-responsive" src="<?php echo $this->basePath($book->getCover()); ?>"
                         alt="<?php echo $book->getName(); ?>"/>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
</div>